# VS integrated REST client

### a simple GET request
GET http://localhost:8000/


### GET request from the integration
# curl ... TODO
GET http://localhost:10001/cards HTTP/1.1
Authorization: Bearer kienbec-mtcgToken

### a POST request from the integration-test script
# curl -i -X POST http://localhost:10001/users --header "Content-Type: application/json" -d "{\"Username\":\"kienboec\", \"Password\":\"daniel\"}"
POST http://localhost:8000/users HTTP/1.1
Content-Type: application/json
{
  "Username":"kienbec"
  "Password":"daniel"
}

