# VS integrated Rest Client


### Create Users
### Should return HTTP 201
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json 
{
  "username":"kienboec",
  "password":"daniel"
}

### Should return HTTP 201
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json
{
  "username": "altenhof",
  "password": "markus"
}

### a POST request from the integration-test script
# curl -i -X POST http://localhost:10001/users --header "Content-Type: application/json" -d "{\"Username\":\"kienboec\", \"Password\":\"daniel\"}"
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json
{
  "username": "Ortwinius",
  "password": "safepassword123"
}


### Should return HTTP 201
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json
{
  "username": "admin",
  "password": "istrator"
}

### Should return HTTP 4xx - User already exists
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json

{
  "username": "kienboec",
  "password": "daniel"
}

### Should return HTTP 4xx - User already exists
POST http://localhost:10001/users HTTP/1.1
Content-Type: application/json

{
  "username": "kienboec",
  "password": "different"
}


### Login Users
### Should return HTTP 200 with generated token for the user, here: kienboec-mtcgToken
POST http://localhost:10001/sessions HTTP/1.1
Content-Type: application/json

{
  "username": "kienboec",
  "password": "daniel"
}

### Should return HTTP 200 with generated token for the user, here: altenhof-mtcgToken
POST http://localhost:10001/sessions HTTP/1.1
Content-Type: application/json

{
  "username": "altenhof",
  "password": "markus"
}

### Should return HTTP 200 with generated token for the user, here: admin-mtcgToken
POST http://localhost:10001/sessions HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "istrator"
}

### Should return HTTP 4xx - Login failed
POST http://localhost:10001/sessions HTTP/1.1
Content-Type: application/json

{
"username": "kienboec",
"password": "wrongpassword"
}

### Should return HTTP 201 - Package created
POST http://localhost:10001/packages HTTP/1.1
Content-Type: application/json
Authorization: Bearer admin-mtcgToken
[
    {
        "id": "845f0dc7-37d0-426e-994e-43fc3ac83c08",
        "name": "WaterGoblin",
        "type": "Monster",
        "element": "Water",
        "damage": 10
    },
    {
        "id": "99f8f8dc-e25e-4a95-aa2c-782823f36e2a",
        "name": "Dragon",
        "type": "Monster",
        "element": "Neutral",
        "damage": 50
    },
    {
        "id": "e85e3976-7c86-4d06-9a80-641c2019a79f",
        "name": "WaterSpell",
        "type": "Spell",
        "element": "Water",
        "damage": 20
    }
]

